// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('google-query_simpleusage', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('google-query_simpleusage', async function() {
    // Test name: google-query_simpleusage
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://mailnesia.com/")
    // 2 | setWindowSize | 1054x848 |  | 
    await driver.manage().window().setRect(1054, 848)
    // 3 | type | name=q | selenium webdriv | 
    await driver.findElement(By.name("q")).sendKeys("selenium webdriv")
    // 4 | sendKeys | name=q | ${KEY_ENTER} | 
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    // 5 | click | css=.tF2Cxc:nth-child(2) .LC20lb |  | 
    await driver.findElement(By.css(".tF2Cxc:nth-child(2) .LC20lb")).click()
  })
})
