// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  public string waitForWindow(int timeout) {
    try {
      Thread.Sleep(timeout);
    } catch(Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
    var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
    if (whNow.Count > whThen.Count) {
      return whNow.Except(whThen).First().ToString();
    } else {
      return whNow.First().ToString();
    }
  }
  [Fact]
  public void Gmailloginsimpleusage() {
    // Test name: gmail-login_simpleusage
    // Step # | name | target | value | comment
    // 1 | open | https://www.google.com/intl/el/gmail/about/# |  | 
    driver.Navigate().GoToUrl("https://www.google.com/intl/el/gmail/about/#");
    // 2 | setWindowSize | 1054x848 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1054, 848);
    // 3 | click | linkText=Σύνδεση |  | 
    vars["WindowHandles"] = driver.WindowHandles;
    // 4 | selectWindow | handle=${win5202} |  | 
    driver.FindElement(By.LinkText("Σύνδεση")).Click();
    // 5 | click | id=identifierId |  | 
    vars["win5202"] = waitForWindow(2000);
    // 6 | type | id=identifierId | testmail11434@gmail.com | 
    driver.SwitchTo().Window(vars["win5202"].ToString());
    // 7 | click | css=.VfPpkd-RLmnJb |  | 
    driver.FindElement(By.Id("identifierId")).Click();
    // 8 | mouseDownAt | id=identifierId | 73.39999389648438,24.399993896484375 | 
    driver.FindElement(By.Id("identifierId")).SendKeys("testmail11434@gmail.com");
    // 9 | mouseMoveAt | id=identifierId | 73.39999389648438,24.399993896484375 | 
    driver.FindElement(By.CssSelector(".VfPpkd-RLmnJb")).Click();
    // 10 | mouseUpAt | id=identifierId | 73.39999389648438,24.399993896484375 | 
    {
      var element = driver.FindElement(By.Id("identifierId"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    // 11 | click | id=identifierId |  | 
    {
      var element = driver.FindElement(By.Id("identifierId"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 12 | type | id=identifierId | testmail1@gmail.com | 
    {
      var element = driver.FindElement(By.Id("identifierId"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    // 13 | click | css=.VfPpkd-RLmnJb |  | 
    driver.FindElement(By.Id("identifierId")).Click();
    // 14 | click | name=password |  | 
    driver.FindElement(By.Id("identifierId")).SendKeys("testmail1@gmail.com");
    // 15 | type | name=password | 345435 | 
    driver.FindElement(By.CssSelector(".VfPpkd-RLmnJb")).Click();
    // 16 | click | css=.VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb |  | 
    driver.FindElement(By.Name("password")).Click();
    // 17 | close |  |  | 
    driver.FindElement(By.Name("password")).SendKeys("345435");
    driver.FindElement(By.CssSelector(".VfPpkd-LgbsSe-OWXEXe-k8QpJ > .VfPpkd-RLmnJb")).Click();
    driver.Close();
  }
}
