// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Googlequerysimpleusage() {
    // Test name: google-query_simpleusage
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.Navigate().GoToUrl("https://www.google.com/intl/el/gmail/about/#/");
    // 2 | setWindowSize | 1054x848 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1054, 848);
    // 3 | type | name=q | selenium webdriv | 
    driver.FindElement(By.Name("q")).SendKeys("selenium webdriv");
    // 4 | sendKeys | name=q | ${KEY_ENTER} | 
    driver.FindElement(By.Name("q")).SendKeys(Keys.Enter);
    // 5 | click | css=.tF2Cxc:nth-child(2) .LC20lb |  | 
    driver.FindElement(By.CssSelector(".tF2Cxc:nth-child(2) .LC20lb")).Click();
  }
}
