// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Googlequery2simpleusage() {
    // Test name: google-query2_simpleusage
    // Step # | name | target | value | comment
    // 1 | open | https://www.google.com/ |  | 
    driver.Navigate().GoToUrl("https://www.google.com/");
    // 2 | setWindowSize | 1054x848 |  | 
    driver.Manage().Window.Size = new System.Drawing.Size(1054, 848);
    // 3 | type | name=q | selenium webdriver | 
    driver.FindElement(By.Name("q")).SendKeys("selenium webdriver");
    // 4 | sendKeys | name=q | ${KEY_ENTER} | 
    driver.FindElement(By.Name("q")).SendKeys(Keys.Enter);
    // 5 | click | css=#\_OJppYNyLAfmKjLsPiYKEmAY16 .KA4pGd |  | 
    driver.FindElement(By.CssSelector("#\\_OJppYNyLAfmKjLsPiYKEmAY16 .KA4pGd")).Click();
    // 6 | click | css=#\_OJppYNyLAfmKjLsPiYKEmAY16 > div |  | 
    driver.FindElement(By.CssSelector("#\\_OJppYNyLAfmKjLsPiYKEmAY16 > div")).Click();
    // 7 | click | css=.g:nth-child(7) .LC20lb |  | 
    driver.FindElement(By.CssSelector(".g:nth-child(7) .LC20lb")).Click();
  }
}
