# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGooglequerysimpleusage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googlequerysimpleusage(self):
    # Test name: google-query_simpleusage
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://mailnesia.com/")
    # 2 | setWindowSize | 1054x848 |  | 
    self.driver.set_window_size(1054, 848)
    # 3 | type | name=q | selenium webdriv | 
    self.driver.find_element(By.NAME, "q").send_keys("selenium webdriv")
    # 4 | sendKeys | name=q | ${KEY_ENTER} | 
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    # 5 | click | css=.tF2Cxc:nth-child(2) .LC20lb |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".tF2Cxc:nth-child(2) .LC20lb").click()
  
