# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGooglequery2simpleusage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_googlequery2simpleusage(self):
    # Test name: google-query2_simpleusage
    # Step # | name | target | value | comment
    # 1 | open | https://www.google.com/ |  | 
    self.driver.get("https://www.google.com/")
    # 2 | setWindowSize | 1054x848 |  | 
    self.driver.set_window_size(1054, 848)
    # 3 | type | name=q | selenium webdriver | 
    self.driver.find_element(By.NAME, "q").send_keys("selenium webdriver")
    # 4 | sendKeys | name=q | ${KEY_ENTER} | 
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    # 5 | click | css=#\_OJppYNyLAfmKjLsPiYKEmAY16 .KA4pGd |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_OJppYNyLAfmKjLsPiYKEmAY16 .KA4pGd").click()
    # 6 | click | css=#\_OJppYNyLAfmKjLsPiYKEmAY16 > div |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_OJppYNyLAfmKjLsPiYKEmAY16 > div").click()
    # 7 | click | css=.g:nth-child(7) .LC20lb |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".g:nth-child(7) .LC20lb").click()
  
